added binding for chat sdk
Softeq/Zendesk-xamarin-android pull request #2
Opened 2022-09-02 13:06 UTC by thisisthekap

Fixes #1

2022-09-06 04:51 UTC, thisisthekap commented
@wcoder Whom should I reach out to to get this PR reviewed & merged?

2022-09-06 09:13 UTC, wcoder commented
/azp run

2022-09-20 13:48 UTC, thisisthekap commented
@wcoder @vadimpylsky @sleushunou Are you able to provide me with the log files of the failed CI build?

2022-09-21 09:44 UTC, wcoder commented
@thisisthekap The review is in progress and takes a lot of time. Thank you for waiting.

Could you please sync with the latest master branch to fix CI check?

2022-09-21 09:46 UTC, thisisthekap commented
@wcoder Did the merge.

2022-09-29 23:49 UTC, wcoder requested changes
Hi @thisisthekap!
Thanks for your contributions! We are we appreciate that 🚀

I'm going to merge this PR, but I have some questions/comments.
Could you please reply to some of them?

2022-09-29 23:49 UTC, wcoder commented on src/JavaCommon.Bindings.Droid/JavaCommon.Bindings.Droid.csproj
> +    <PackageReference Include="GoogleGson">
Based on sources, required only:
- (Square.Retrofit2 & GoogleGson) or only Square.Retrofit2.ConverterGson

2022-09-29 23:49 UTC, wcoder commented on nuget/Softeq.ZendeskBelvedere.nuspec
> +                <dependency id="Square.Picasso" version="2.8.0.5" />
Please review dependencies, and add only those required for binding.
`Square.Picasso` already contains `Square.OkHttp3`

2022-09-29 23:49 UTC, wcoder commented on src/Belvedere.Bindings.Droid/Belvedere.Bindings.Droid.csproj
> +    </PackageReference>
Please review dependencies, and add only those required for binding.

2022-09-29 23:49 UTC, wcoder commented on src/CommonUI.Bindings.Droid/CommonUI.Bindings.Droid.csproj
> +    <PackageReference Include="Xamarin.AndroidX.AppCompat">
Please review dependencies, and add only those required for binding.

2022-09-29 23:49 UTC, wcoder commented on src/ConfigurationSDK.Bindings.Droid/ConfigurationSDK.Bindings.Droid.csproj
> +    <PackageReference Include="Xamarin.AndroidX.Annotation">
Please review dependencies, and add only those required for binding.

2022-09-29 23:49 UTC, wcoder commented on src/CoreSDK.Bindings.Droid/CoreSDK.Bindings.Droid.csproj
> +    <PackageReference Include="GoogleGson">
Please review dependencies, and add only those required for binding.

2022-09-29 23:49 UTC, wcoder commented on src/Guide.Bindings.Droid/Guide.Bindings.Droid.csproj
> +      <Version>1.3.1.5</Version>
Please review dependencies, and add only those required for binding.

2022-09-29 23:49 UTC, wcoder commented on src/Messaging.Bindings.Droid/Messaging.Bindings.Droid.csproj
> +    </PackageReference>
Please review dependencies, and add only those required for binding.

2022-09-29 23:49 UTC, wcoder commented on src/SupportProvidersSDK.Bindings.Droid/SupportProvidersSDK.Bindings.Droid.csproj
> +  <ItemGroup>
Please review dependencies, and add only those required for binding.

2022-09-29 23:49 UTC, wcoder commented on src/SupportSDK.Bindings.Droid/SupportSDK.Bindings.Droid.csproj
> +    <PackageReference Include="Xamarin.AndroidX.Fragment">
Please review dependencies, and add only those required for binding.

2022-09-29 23:49 UTC, wcoder commented on nuget/Softeq.ZendeskSuas.nuspec
> +        <version>1.2.0.3</version>
No need because the native library is the same.

2022-09-29 23:49 UTC, wcoder commented on nuget/Softeq.ZendeskSupportProviders.Droid.nuspec
> +                <dependency id="Softeq.ZendeskCore.Droid" version="4.0.8.3" />
Are we really need all dependencies for use?

2022-10-03 14:27 UTC, thisisthekap commented on src/Belvedere.Bindings.Droid/belvedere-dependencies.txt
> +androidx.core:core:1.3.1 compile
This is jsut extracted from the pom files.

2022-10-03 14:27 UTC, thisisthekap commented on .gitignore
> +library_project_jars/
They are created by the IDE and/or the build process. These artifacts must therefore not be checked in to my point of view.

2022-10-03 14:30 UTC, thisisthekap commented on nuget/Softeq.ZendeskSupport.Droid.nuspec
> +        <version>5.0.2.3</version>
You are right. I am going to fix this.

2022-10-03 14:30 UTC, thisisthekap commented on nuget/Softeq.ZendeskSupportProviders.Droid.nuspec
> +        <version>5.1.0.3</version>
You are right. I am going to fix this.

2022-10-03 14:30 UTC, thisisthekap commented on src/JavaCommon.Bindings.Droid/java-common-dependencies.txt
> +org.jetbrains.kotlin:kotlin-stdlib:1.4.32 compile
According to its dependeicies: Yes.

2022-10-03 14:31 UTC, thisisthekap commented on src/Messaging.Bindings.Droid/Messaging.Bindings.Droid.csproj
> +    </PackageReference>
I added only those which are referenced by the java library.

2022-10-03 14:31 UTC, thisisthekap commented on src/SupportProvidersSDK.Bindings.Droid/SupportProvidersSDK.Bindings.Droid.csproj
> +  <ItemGroup>
I added only those which are referenced by the java library.

2022-10-03 14:31 UTC, thisisthekap commented on src/SupportSDK.Bindings.Droid/SupportSDK.Bindings.Droid.csproj
> +    <PackageReference Include="Xamarin.AndroidX.Fragment">
I added only those which are referenced by the java library.

2022-10-03 14:31 UTC, thisisthekap commented on nuget/Softeq.ZendeskSuas.nuspec
> +        <version>1.2.0.3</version>
Will review.

2022-10-14 13:07 UTC, wcoder approved these changes

2022-10-14 13:08 UTC, merged